version: '3.8'

services:
  postgres:
    container_name: postgres_container
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - postgres:${PGDATA:-/data/postgres}
    ports:
      - '${TYPEORM_PORT}:${TYPEORM_PORT}'
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - postgres
    restart: no
    ports:
      - '${API_PORT}:3000'
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_HOST=postgres



volumes:
  postgres:
  backend:
