# Используем базовый образ Node.js с предустановленным npm
FROM node:18-alpine-slim

WORKDIR /app

# Копируем package.json и устанавливаем зависимости с помощью npm
COPY package.json ./
RUN npm install

# Копируем остальные файлы проекта
COPY . .

# Экспозиция порта
EXPOSE 3030

# Команда для запуска приложения
CMD ["npm", "start"]
